### ISSUE TITLE
Xenial EOL

### ISSUE THREAD

**Issue by babrodtk** [metno/snap#44]
```connection = SSHConnection(machine="xvis-m3b.met.no", port=22)``` in https://github.com/metno/snap/blob/c00bfd361929e634029a1ad59296cd15022ea290/utils/SnapPy/METNO/PPI.py
may be a problem when migrating to focal.

**Comment by heikoklein** [comment]
Good that we use PPI_direct.py (i.e. no ssh-connection) and not PPI.py. PPI.py should eventually be deleted, but is no problem.
